name: Test & Lint Feature Branch

on:
  pull_request:

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Info
        run: echo "GITHUB_REF is $GITHUB_REF"
      - name: Check Branch Name Convention
        run: |
          branch_name=$(echo $GITHUB_REF | sed -e 's,.*/\(.*\),\1,')
          if [[ ! "$branch_name" =~ ^(feat|fix|docs|style|refactor|perf|test|ci|chore)/.*$ ]]; then
            echo "Invalid branch name. Branch names must follow the convention."
            exit 1
          fi

  test-coverage:
    runs-on: ubuntu-latest
    needs: enforce-branch-naming
    if: needs.enforce-branch-naming.result == 'success'
    steps:
      - uses: actions/checkout@v2

      - uses: ArtiomTr/jest-coverage-report-action@v2

  lint:
    runs-on: ubuntu-latest
    needs: test-coverage
    if: needs.test-coverage.result == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint Checks
        run: npm run lint
