name: Lint, Test and Build Feature Branch

on:
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install

      - name: Build the App
        run: npm run build  # Adjust the build command as needed

      - name: Run ESLint Checks
        run: npm run lint  # Adjust the linting command as needed