name: Lint React Native Expo App

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: eslint src/* # Adjust the linting command as needed