name: Test & Lint Feature Branch

on:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ArtiomTr/jest-coverage-report-action@v2

  build-and-lint:
    runs-on: ubuntu-latest
    needs: coverage
    if: needs.coverage.result == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint Checks
        run: npm run lint
